### ISSUE TITLE
Prop Spinner Bug

### ISSUE THREAD

**Issue by zeta976** [zeta976/Cessna-152#8]
Propeller spinner "moving" object shows with engine off.

**Comment by gplv34** [comment]
I noticed the flickering spinner appears on a windy day.  Fixed it by making it stay hidden even when turning backwards - at the end of Fuselage.obj: 0 becomes -30 in lines 114477 and 114535

	ANIM_hide	-30	200	sim/cockpit2/engine/indicators/prop_speed_rpm[0]
